"""Добавление нового поля

Revision ID: 3674e2f20c03
Revises: 4e749a42572c
Create Date: 2025-05-21 16:28:19.994768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3674e2f20c03'
down_revision: Union[str, None] = '4e749a42572c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_in_work', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['user_in_work'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_in_work')
    # ### end Alembic commands ###
